/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeUserRouteRouteImport } from './routes/_home/user/route'
import { Route as HomeUserIndexRouteImport } from './routes/_home/user/index'
import { Route as HomeSearchIndexRouteImport } from './routes/_home/search/index'
import { Route as HomeProductIndexRouteImport } from './routes/_home/product/index'
import { Route as HomeOrdersIndexRouteImport } from './routes/_home/orders/index'
import { Route as HomeContactUsIndexRouteImport } from './routes/_home/contact-us/index'
import { Route as HomeCheckoutIndexRouteImport } from './routes/_home/checkout/index'
import { Route as HomeAboutUsIndexRouteImport } from './routes/_home/about-us/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as HomeProductProductIdRouteImport } from './routes/_home/product/$productId'
import { Route as HomeOrdersOrderIdRouteImport } from './routes/_home/orders/$orderId'
import { Route as HomeUserUpdateProfileIndexRouteImport } from './routes/_home/user/update-profile/index'
import { Route as HomeUserOrdersIndexRouteImport } from './routes/_home/user/orders/index'
import { Route as HomeUserDashboardIndexRouteImport } from './routes/_home/user/dashboard/index'
import { Route as HomeUserChangePasswordIndexRouteImport } from './routes/_home/user/change-password/index'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeUserRouteRoute = HomeUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeUserIndexRoute = HomeUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeUserRouteRoute,
} as any)
const HomeSearchIndexRoute = HomeSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeProductIndexRoute = HomeProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeOrdersIndexRoute = HomeOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeContactUsIndexRoute = HomeContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCheckoutIndexRoute = HomeCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAboutUsIndexRoute = HomeAboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeProductProductIdRoute = HomeProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeOrdersOrderIdRoute = HomeOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeUserUpdateProfileIndexRoute =
  HomeUserUpdateProfileIndexRouteImport.update({
    id: '/update-profile/',
    path: '/update-profile/',
    getParentRoute: () => HomeUserRouteRoute,
  } as any)
const HomeUserOrdersIndexRoute = HomeUserOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => HomeUserRouteRoute,
} as any)
const HomeUserDashboardIndexRoute = HomeUserDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => HomeUserRouteRoute,
} as any)
const HomeUserChangePasswordIndexRoute =
  HomeUserChangePasswordIndexRouteImport.update({
    id: '/change-password/',
    path: '/change-password/',
    getParentRoute: () => HomeUserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof HomeUserRouteRouteWithChildren
  '/orders/$orderId': typeof HomeOrdersOrderIdRoute
  '/product/$productId': typeof HomeProductProductIdRoute
  '/login/': typeof AuthLoginIndexRoute
  '/about-us/': typeof HomeAboutUsIndexRoute
  '/checkout/': typeof HomeCheckoutIndexRoute
  '/contact-us/': typeof HomeContactUsIndexRoute
  '/orders/': typeof HomeOrdersIndexRoute
  '/product/': typeof HomeProductIndexRoute
  '/search/': typeof HomeSearchIndexRoute
  '/user/': typeof HomeUserIndexRoute
  '/user/change-password/': typeof HomeUserChangePasswordIndexRoute
  '/user/dashboard/': typeof HomeUserDashboardIndexRoute
  '/user/orders/': typeof HomeUserOrdersIndexRoute
  '/user/update-profile/': typeof HomeUserUpdateProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orders/$orderId': typeof HomeOrdersOrderIdRoute
  '/product/$productId': typeof HomeProductProductIdRoute
  '/login': typeof AuthLoginIndexRoute
  '/about-us': typeof HomeAboutUsIndexRoute
  '/checkout': typeof HomeCheckoutIndexRoute
  '/contact-us': typeof HomeContactUsIndexRoute
  '/orders': typeof HomeOrdersIndexRoute
  '/product': typeof HomeProductIndexRoute
  '/search': typeof HomeSearchIndexRoute
  '/user': typeof HomeUserIndexRoute
  '/user/change-password': typeof HomeUserChangePasswordIndexRoute
  '/user/dashboard': typeof HomeUserDashboardIndexRoute
  '/user/orders': typeof HomeUserOrdersIndexRoute
  '/user/update-profile': typeof HomeUserUpdateProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_home': typeof HomeRouteRouteWithChildren
  '/_home/user': typeof HomeUserRouteRouteWithChildren
  '/_home/orders/$orderId': typeof HomeOrdersOrderIdRoute
  '/_home/product/$productId': typeof HomeProductProductIdRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_home/about-us/': typeof HomeAboutUsIndexRoute
  '/_home/checkout/': typeof HomeCheckoutIndexRoute
  '/_home/contact-us/': typeof HomeContactUsIndexRoute
  '/_home/orders/': typeof HomeOrdersIndexRoute
  '/_home/product/': typeof HomeProductIndexRoute
  '/_home/search/': typeof HomeSearchIndexRoute
  '/_home/user/': typeof HomeUserIndexRoute
  '/_home/user/change-password/': typeof HomeUserChangePasswordIndexRoute
  '/_home/user/dashboard/': typeof HomeUserDashboardIndexRoute
  '/_home/user/orders/': typeof HomeUserOrdersIndexRoute
  '/_home/user/update-profile/': typeof HomeUserUpdateProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/orders/$orderId'
    | '/product/$productId'
    | '/login/'
    | '/about-us/'
    | '/checkout/'
    | '/contact-us/'
    | '/orders/'
    | '/product/'
    | '/search/'
    | '/user/'
    | '/user/change-password/'
    | '/user/dashboard/'
    | '/user/orders/'
    | '/user/update-profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/orders/$orderId'
    | '/product/$productId'
    | '/login'
    | '/about-us'
    | '/checkout'
    | '/contact-us'
    | '/orders'
    | '/product'
    | '/search'
    | '/user'
    | '/user/change-password'
    | '/user/dashboard'
    | '/user/orders'
    | '/user/update-profile'
  id:
    | '__root__'
    | '/'
    | '/_home'
    | '/_home/user'
    | '/_home/orders/$orderId'
    | '/_home/product/$productId'
    | '/_auth/login/'
    | '/_home/about-us/'
    | '/_home/checkout/'
    | '/_home/contact-us/'
    | '/_home/orders/'
    | '/_home/product/'
    | '/_home/search/'
    | '/_home/user/'
    | '/_home/user/change-password/'
    | '/_home/user/dashboard/'
    | '/_home/user/orders/'
    | '/_home/user/update-profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/user': {
      id: '/_home/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof HomeUserRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/user/': {
      id: '/_home/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof HomeUserIndexRouteImport
      parentRoute: typeof HomeUserRouteRoute
    }
    '/_home/search/': {
      id: '/_home/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof HomeSearchIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/product/': {
      id: '/_home/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof HomeProductIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/orders/': {
      id: '/_home/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof HomeOrdersIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/contact-us/': {
      id: '/_home/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us/'
      preLoaderRoute: typeof HomeContactUsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/checkout/': {
      id: '/_home/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof HomeCheckoutIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/about-us/': {
      id: '/_home/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof HomeAboutUsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/product/$productId': {
      id: '/_home/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof HomeProductProductIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/orders/$orderId': {
      id: '/_home/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof HomeOrdersOrderIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/user/update-profile/': {
      id: '/_home/user/update-profile/'
      path: '/update-profile'
      fullPath: '/user/update-profile/'
      preLoaderRoute: typeof HomeUserUpdateProfileIndexRouteImport
      parentRoute: typeof HomeUserRouteRoute
    }
    '/_home/user/orders/': {
      id: '/_home/user/orders/'
      path: '/orders'
      fullPath: '/user/orders/'
      preLoaderRoute: typeof HomeUserOrdersIndexRouteImport
      parentRoute: typeof HomeUserRouteRoute
    }
    '/_home/user/dashboard/': {
      id: '/_home/user/dashboard/'
      path: '/dashboard'
      fullPath: '/user/dashboard/'
      preLoaderRoute: typeof HomeUserDashboardIndexRouteImport
      parentRoute: typeof HomeUserRouteRoute
    }
    '/_home/user/change-password/': {
      id: '/_home/user/change-password/'
      path: '/change-password'
      fullPath: '/user/change-password/'
      preLoaderRoute: typeof HomeUserChangePasswordIndexRouteImport
      parentRoute: typeof HomeUserRouteRoute
    }
  }
}

interface HomeUserRouteRouteChildren {
  HomeUserIndexRoute: typeof HomeUserIndexRoute
  HomeUserChangePasswordIndexRoute: typeof HomeUserChangePasswordIndexRoute
  HomeUserDashboardIndexRoute: typeof HomeUserDashboardIndexRoute
  HomeUserOrdersIndexRoute: typeof HomeUserOrdersIndexRoute
  HomeUserUpdateProfileIndexRoute: typeof HomeUserUpdateProfileIndexRoute
}

const HomeUserRouteRouteChildren: HomeUserRouteRouteChildren = {
  HomeUserIndexRoute: HomeUserIndexRoute,
  HomeUserChangePasswordIndexRoute: HomeUserChangePasswordIndexRoute,
  HomeUserDashboardIndexRoute: HomeUserDashboardIndexRoute,
  HomeUserOrdersIndexRoute: HomeUserOrdersIndexRoute,
  HomeUserUpdateProfileIndexRoute: HomeUserUpdateProfileIndexRoute,
}

const HomeUserRouteRouteWithChildren = HomeUserRouteRoute._addFileChildren(
  HomeUserRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeUserRouteRoute: typeof HomeUserRouteRouteWithChildren
  HomeOrdersOrderIdRoute: typeof HomeOrdersOrderIdRoute
  HomeProductProductIdRoute: typeof HomeProductProductIdRoute
  HomeAboutUsIndexRoute: typeof HomeAboutUsIndexRoute
  HomeCheckoutIndexRoute: typeof HomeCheckoutIndexRoute
  HomeContactUsIndexRoute: typeof HomeContactUsIndexRoute
  HomeOrdersIndexRoute: typeof HomeOrdersIndexRoute
  HomeProductIndexRoute: typeof HomeProductIndexRoute
  HomeSearchIndexRoute: typeof HomeSearchIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeUserRouteRoute: HomeUserRouteRouteWithChildren,
  HomeOrdersOrderIdRoute: HomeOrdersOrderIdRoute,
  HomeProductProductIdRoute: HomeProductProductIdRoute,
  HomeAboutUsIndexRoute: HomeAboutUsIndexRoute,
  HomeCheckoutIndexRoute: HomeCheckoutIndexRoute,
  HomeContactUsIndexRoute: HomeContactUsIndexRoute,
  HomeOrdersIndexRoute: HomeOrdersIndexRoute,
  HomeProductIndexRoute: HomeProductIndexRoute,
  HomeSearchIndexRoute: HomeSearchIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
