/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeProtectedRouteRouteImport } from './routes/_home/_protected/route'
import { Route as HomeSearchIndexRouteImport } from './routes/_home/search/index'
import { Route as HomeProductIndexRouteImport } from './routes/_home/product/index'
import { Route as HomeContactUsIndexRouteImport } from './routes/_home/contact-us/index'
import { Route as HomeAboutUsIndexRouteImport } from './routes/_home/about-us/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as HomeProductProductIdRouteImport } from './routes/_home/product/$productId'
import { Route as HomeProtectedUserRouteRouteImport } from './routes/_home/_protected/user/route'
import { Route as HomeProtectedUserIndexRouteImport } from './routes/_home/_protected/user/index'
import { Route as HomeProtectedOrdersIndexRouteImport } from './routes/_home/_protected/orders/index'
import { Route as HomeProtectedCheckoutIndexRouteImport } from './routes/_home/_protected/checkout/index'
import { Route as HomeProtectedOrdersOrderIdRouteImport } from './routes/_home/_protected/orders/$orderId'
import { Route as HomeProtectedUserUpdateProfileIndexRouteImport } from './routes/_home/_protected/user/update-profile/index'
import { Route as HomeProtectedUserOrdersIndexRouteImport } from './routes/_home/_protected/user/orders/index'
import { Route as HomeProtectedUserDashboardIndexRouteImport } from './routes/_home/_protected/user/dashboard/index'
import { Route as HomeProtectedUserChangePasswordIndexRouteImport } from './routes/_home/_protected/user/change-password/index'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeProtectedRouteRoute = HomeProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSearchIndexRoute = HomeSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeProductIndexRoute = HomeProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeContactUsIndexRoute = HomeContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAboutUsIndexRoute = HomeAboutUsIndexRouteImport.update({
  id: '/about-us/',
  path: '/about-us/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const HomeProductProductIdRoute = HomeProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeProtectedUserRouteRoute = HomeProtectedUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => HomeProtectedRouteRoute,
} as any)
const HomeProtectedUserIndexRoute = HomeProtectedUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeProtectedUserRouteRoute,
} as any)
const HomeProtectedOrdersIndexRoute =
  HomeProtectedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => HomeProtectedRouteRoute,
  } as any)
const HomeProtectedCheckoutIndexRoute =
  HomeProtectedCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => HomeProtectedRouteRoute,
  } as any)
const HomeProtectedOrdersOrderIdRoute =
  HomeProtectedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => HomeProtectedRouteRoute,
  } as any)
const HomeProtectedUserUpdateProfileIndexRoute =
  HomeProtectedUserUpdateProfileIndexRouteImport.update({
    id: '/update-profile/',
    path: '/update-profile/',
    getParentRoute: () => HomeProtectedUserRouteRoute,
  } as any)
const HomeProtectedUserOrdersIndexRoute =
  HomeProtectedUserOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => HomeProtectedUserRouteRoute,
  } as any)
const HomeProtectedUserDashboardIndexRoute =
  HomeProtectedUserDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => HomeProtectedUserRouteRoute,
  } as any)
const HomeProtectedUserChangePasswordIndexRoute =
  HomeProtectedUserChangePasswordIndexRouteImport.update({
    id: '/change-password/',
    path: '/change-password/',
    getParentRoute: () => HomeProtectedUserRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/user': typeof HomeProtectedUserRouteRouteWithChildren
  '/product/$productId': typeof HomeProductProductIdRoute
  '/login/': typeof AuthLoginIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/about-us/': typeof HomeAboutUsIndexRoute
  '/contact-us/': typeof HomeContactUsIndexRoute
  '/product/': typeof HomeProductIndexRoute
  '/search/': typeof HomeSearchIndexRoute
  '/orders/$orderId': typeof HomeProtectedOrdersOrderIdRoute
  '/checkout/': typeof HomeProtectedCheckoutIndexRoute
  '/orders/': typeof HomeProtectedOrdersIndexRoute
  '/user/': typeof HomeProtectedUserIndexRoute
  '/user/change-password/': typeof HomeProtectedUserChangePasswordIndexRoute
  '/user/dashboard/': typeof HomeProtectedUserDashboardIndexRoute
  '/user/orders/': typeof HomeProtectedUserOrdersIndexRoute
  '/user/update-profile/': typeof HomeProtectedUserUpdateProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/product/$productId': typeof HomeProductProductIdRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/about-us': typeof HomeAboutUsIndexRoute
  '/contact-us': typeof HomeContactUsIndexRoute
  '/product': typeof HomeProductIndexRoute
  '/search': typeof HomeSearchIndexRoute
  '/orders/$orderId': typeof HomeProtectedOrdersOrderIdRoute
  '/checkout': typeof HomeProtectedCheckoutIndexRoute
  '/orders': typeof HomeProtectedOrdersIndexRoute
  '/user': typeof HomeProtectedUserIndexRoute
  '/user/change-password': typeof HomeProtectedUserChangePasswordIndexRoute
  '/user/dashboard': typeof HomeProtectedUserDashboardIndexRoute
  '/user/orders': typeof HomeProtectedUserOrdersIndexRoute
  '/user/update-profile': typeof HomeProtectedUserUpdateProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/_home/_protected': typeof HomeProtectedRouteRouteWithChildren
  '/_home/': typeof HomeIndexRoute
  '/_home/_protected/user': typeof HomeProtectedUserRouteRouteWithChildren
  '/_home/product/$productId': typeof HomeProductProductIdRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_home/about-us/': typeof HomeAboutUsIndexRoute
  '/_home/contact-us/': typeof HomeContactUsIndexRoute
  '/_home/product/': typeof HomeProductIndexRoute
  '/_home/search/': typeof HomeSearchIndexRoute
  '/_home/_protected/orders/$orderId': typeof HomeProtectedOrdersOrderIdRoute
  '/_home/_protected/checkout/': typeof HomeProtectedCheckoutIndexRoute
  '/_home/_protected/orders/': typeof HomeProtectedOrdersIndexRoute
  '/_home/_protected/user/': typeof HomeProtectedUserIndexRoute
  '/_home/_protected/user/change-password/': typeof HomeProtectedUserChangePasswordIndexRoute
  '/_home/_protected/user/dashboard/': typeof HomeProtectedUserDashboardIndexRoute
  '/_home/_protected/user/orders/': typeof HomeProtectedUserOrdersIndexRoute
  '/_home/_protected/user/update-profile/': typeof HomeProtectedUserUpdateProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/product/$productId'
    | '/login/'
    | '/register/'
    | '/about-us/'
    | '/contact-us/'
    | '/product/'
    | '/search/'
    | '/orders/$orderId'
    | '/checkout/'
    | '/orders/'
    | '/user/'
    | '/user/change-password/'
    | '/user/dashboard/'
    | '/user/orders/'
    | '/user/update-profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product/$productId'
    | '/login'
    | '/register'
    | '/about-us'
    | '/contact-us'
    | '/product'
    | '/search'
    | '/orders/$orderId'
    | '/checkout'
    | '/orders'
    | '/user'
    | '/user/change-password'
    | '/user/dashboard'
    | '/user/orders'
    | '/user/update-profile'
  id:
    | '__root__'
    | '/_auth'
    | '/_home'
    | '/_home/_protected'
    | '/_home/'
    | '/_home/_protected/user'
    | '/_home/product/$productId'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_home/about-us/'
    | '/_home/contact-us/'
    | '/_home/product/'
    | '/_home/search/'
    | '/_home/_protected/orders/$orderId'
    | '/_home/_protected/checkout/'
    | '/_home/_protected/orders/'
    | '/_home/_protected/user/'
    | '/_home/_protected/user/change-password/'
    | '/_home/_protected/user/dashboard/'
    | '/_home/_protected/user/orders/'
    | '/_home/_protected/user/update-profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/_protected': {
      id: '/_home/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeProtectedRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/search/': {
      id: '/_home/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof HomeSearchIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/product/': {
      id: '/_home/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof HomeProductIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/contact-us/': {
      id: '/_home/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us/'
      preLoaderRoute: typeof HomeContactUsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/about-us/': {
      id: '/_home/about-us/'
      path: '/about-us'
      fullPath: '/about-us/'
      preLoaderRoute: typeof HomeAboutUsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_home/product/$productId': {
      id: '/_home/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof HomeProductProductIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/_protected/user': {
      id: '/_home/_protected/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof HomeProtectedUserRouteRouteImport
      parentRoute: typeof HomeProtectedRouteRoute
    }
    '/_home/_protected/user/': {
      id: '/_home/_protected/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof HomeProtectedUserIndexRouteImport
      parentRoute: typeof HomeProtectedUserRouteRoute
    }
    '/_home/_protected/orders/': {
      id: '/_home/_protected/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof HomeProtectedOrdersIndexRouteImport
      parentRoute: typeof HomeProtectedRouteRoute
    }
    '/_home/_protected/checkout/': {
      id: '/_home/_protected/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof HomeProtectedCheckoutIndexRouteImport
      parentRoute: typeof HomeProtectedRouteRoute
    }
    '/_home/_protected/orders/$orderId': {
      id: '/_home/_protected/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof HomeProtectedOrdersOrderIdRouteImport
      parentRoute: typeof HomeProtectedRouteRoute
    }
    '/_home/_protected/user/update-profile/': {
      id: '/_home/_protected/user/update-profile/'
      path: '/update-profile'
      fullPath: '/user/update-profile/'
      preLoaderRoute: typeof HomeProtectedUserUpdateProfileIndexRouteImport
      parentRoute: typeof HomeProtectedUserRouteRoute
    }
    '/_home/_protected/user/orders/': {
      id: '/_home/_protected/user/orders/'
      path: '/orders'
      fullPath: '/user/orders/'
      preLoaderRoute: typeof HomeProtectedUserOrdersIndexRouteImport
      parentRoute: typeof HomeProtectedUserRouteRoute
    }
    '/_home/_protected/user/dashboard/': {
      id: '/_home/_protected/user/dashboard/'
      path: '/dashboard'
      fullPath: '/user/dashboard/'
      preLoaderRoute: typeof HomeProtectedUserDashboardIndexRouteImport
      parentRoute: typeof HomeProtectedUserRouteRoute
    }
    '/_home/_protected/user/change-password/': {
      id: '/_home/_protected/user/change-password/'
      path: '/change-password'
      fullPath: '/user/change-password/'
      preLoaderRoute: typeof HomeProtectedUserChangePasswordIndexRouteImport
      parentRoute: typeof HomeProtectedUserRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HomeProtectedUserRouteRouteChildren {
  HomeProtectedUserIndexRoute: typeof HomeProtectedUserIndexRoute
  HomeProtectedUserChangePasswordIndexRoute: typeof HomeProtectedUserChangePasswordIndexRoute
  HomeProtectedUserDashboardIndexRoute: typeof HomeProtectedUserDashboardIndexRoute
  HomeProtectedUserOrdersIndexRoute: typeof HomeProtectedUserOrdersIndexRoute
  HomeProtectedUserUpdateProfileIndexRoute: typeof HomeProtectedUserUpdateProfileIndexRoute
}

const HomeProtectedUserRouteRouteChildren: HomeProtectedUserRouteRouteChildren =
  {
    HomeProtectedUserIndexRoute: HomeProtectedUserIndexRoute,
    HomeProtectedUserChangePasswordIndexRoute:
      HomeProtectedUserChangePasswordIndexRoute,
    HomeProtectedUserDashboardIndexRoute: HomeProtectedUserDashboardIndexRoute,
    HomeProtectedUserOrdersIndexRoute: HomeProtectedUserOrdersIndexRoute,
    HomeProtectedUserUpdateProfileIndexRoute:
      HomeProtectedUserUpdateProfileIndexRoute,
  }

const HomeProtectedUserRouteRouteWithChildren =
  HomeProtectedUserRouteRoute._addFileChildren(
    HomeProtectedUserRouteRouteChildren,
  )

interface HomeProtectedRouteRouteChildren {
  HomeProtectedUserRouteRoute: typeof HomeProtectedUserRouteRouteWithChildren
  HomeProtectedOrdersOrderIdRoute: typeof HomeProtectedOrdersOrderIdRoute
  HomeProtectedCheckoutIndexRoute: typeof HomeProtectedCheckoutIndexRoute
  HomeProtectedOrdersIndexRoute: typeof HomeProtectedOrdersIndexRoute
}

const HomeProtectedRouteRouteChildren: HomeProtectedRouteRouteChildren = {
  HomeProtectedUserRouteRoute: HomeProtectedUserRouteRouteWithChildren,
  HomeProtectedOrdersOrderIdRoute: HomeProtectedOrdersOrderIdRoute,
  HomeProtectedCheckoutIndexRoute: HomeProtectedCheckoutIndexRoute,
  HomeProtectedOrdersIndexRoute: HomeProtectedOrdersIndexRoute,
}

const HomeProtectedRouteRouteWithChildren =
  HomeProtectedRouteRoute._addFileChildren(HomeProtectedRouteRouteChildren)

interface HomeRouteRouteChildren {
  HomeProtectedRouteRoute: typeof HomeProtectedRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
  HomeProductProductIdRoute: typeof HomeProductProductIdRoute
  HomeAboutUsIndexRoute: typeof HomeAboutUsIndexRoute
  HomeContactUsIndexRoute: typeof HomeContactUsIndexRoute
  HomeProductIndexRoute: typeof HomeProductIndexRoute
  HomeSearchIndexRoute: typeof HomeSearchIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeProtectedRouteRoute: HomeProtectedRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
  HomeProductProductIdRoute: HomeProductProductIdRoute,
  HomeAboutUsIndexRoute: HomeAboutUsIndexRoute,
  HomeContactUsIndexRoute: HomeContactUsIndexRoute,
  HomeProductIndexRoute: HomeProductIndexRoute,
  HomeSearchIndexRoute: HomeSearchIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
